### ISSUE TITLE
Missing method suffix in order to run with current master of VBoxAdm

### ISSUE THREAD

**Issue by level420** [dominikschulz/Log-Tree#2]
While trying to configure and install the current master of https://github.com/dominikschulz/VBoxAdm, where Log::Tree is used, I'm getting error messages in VBoxAdms Frontend.pm and API.pm where an, at least for the version here and at cpan, the mehtod suffix is not known.

Please, if possible and someone is listening here, add that method and publish it to cpan.

That would be great
Thank you

Best regards

**Comment by dominikschulz** [comment]
Thank you for reporting this. Release 0.17 which implements the suffix method needed for VBoxAdm master.

Please note that installing VBoxAdm from master is not recommended. You should use the latest release version unless you want to hack on the source.
